[package]
name = "rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
proc-macro2 = { version = "1.0.79", features = ["span-locations"] }
quote = "1.0.35"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
syn = { version = "2.0.53", features = ["full", "visit"] }
wasm-bindgen = { version = "0.2.92", features = ["serde-serialize"] }
