name: E2E Tests

on: pull_request

env:
  WASM_PACK_VERSION: 0.12.1

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm build:pkg

      - run: xvfb-run -a pnpm -F sqlsurge test
        if: runner.os == 'Linux'

      - run: pnpm -F sqlsurge test
        if: runner.os != 'Linux'
